AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - jw.io::cv19-mars
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Cv19MarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: jw.io.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/cv19-mars-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Cv19MarsApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Cv19MarsApi
